config/routes.rb
Rails.application.routes.draw do
  resources :controllers
  root "articles#index"

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    
  end
  

app/models/controller.rb
class Controller < ApplicationRecord
end

app/models/t.rb
class T < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
      @articles = Article.all
    end
  
    def show

      @article = Article.find(params[:id])
    end
  
    def new
        @article = Article.new
      
    end
  
    def create
      @article = Article.new(article_params)
  
      if @article.save
        redirect_to @article
      else
        render :new, status: :unprocessable_entity
      end
    end


    def edit
      @article = Article.find(params[:id])
    end
  
    def update
      @article = Article.find(params[:id])
  
      if @article.update(article_params)
        redirect_to @article
      else
        render :edit, status: :unprocessable_entity
      end
    end

      def destroy
        @article = Article.find(params[:id])
        @article.destroy
    
        redirect_to root_path, status: :see_other
      end


  
    private
      def article_params
        params.require(:article).permit(:title, :body)
      end
  end
  

app/controllers/controllers_controller.rb
class ControllersController < ApplicationController
  before_action :set_controller, only: %i[ show edit update destroy ]

  # GET /controllers or /controllers.json
  def index
    @controllers = Controller.all
  end

  # GET /controllers/1 or /controllers/1.json
  def show
  end

  # GET /controllers/new
  def new
    @controller = Controller.new
  end

  # GET /controllers/1/edit
  def edit
  end

  # POST /controllers or /controllers.json
  def create
    @controller = Controller.new(controller_params)

    respond_to do |format|
      if @controller.save
        format.html { redirect_to controller_url(@controller), notice: "Controller was successfully created." }
        format.json { render :show, status: :created, location: @controller }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @controller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /controllers/1 or /controllers/1.json
  def update
    respond_to do |format|
      if @controller.update(controller_params)
        format.html { redirect_to controller_url(@controller), notice: "Controller was successfully updated." }
        format.json { render :show, status: :ok, location: @controller }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @controller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /controllers/1 or /controllers/1.json
  def destroy
    @controller.destroy

    respond_to do |format|
      format.html { redirect_to controllers_url, notice: "Controller was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_controller
      @controller = Controller.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def controller_params
      params.require(:controller).permit(:t)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/controllers_helper.rb
module ControllersHelper
end

app/views/articles/_form.html.erb
  <div class="card shadow-lg" style="width: 18rem;">
    <div class="card-body">
      

      <%= form_with model: article, class: 'needs-validation', novalidate: true do |form| %>
  <div class="mb-3">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control', required: true %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div class="invalid-feedback"><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :body, class: 'form-label' %>
    <%= form.text_area :body, class: 'form-control', required: true %>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div class="invalid-feedback"><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>





    </div>
  </div>

app/views/articles/edit.html.erb
<div class="d-flex justify-content-center align-items-center flex-column" style="height: 80vh;">
<h1>Edit Article</h1>
      <%= render "form", article: @article %>
   <div>

app/views/articles/index.html.erb
<div class="d-flex flex-column justify-content-center align-items-center" style="height: 100vh;">
  <div class = "fs-5 t= fw-bold my-5">
    <h1>Articles</h1>
  </div>
  
  <% @articles.each do |article| %>
    <div class="card my-3 shadow" style="width: 18rem;">
      <div class="card-body text-center">
        <h5 class="card-title"><%= article.title %></h5>
        <div class="d-grid gap-2 col-6 mx-auto">
        <button type="button full" class="btn btn-success">
          <%= link_to "Go", article, style: "color: white; text-decoration: none;" %>
        </button>
        </div>
      </div>
    </div>
  <% end %>
  <button type="button" class="btn btn-danger mt-3">
       <%= link_to "Create New Blog", new_article_path , style: "color: white; text-decoration: none;"  %>
      </button>
</div>






 

app/views/articles/new.html.erb
<div class="d-flex justify-content-center align-items-center flex-column" style="height: 80vh;">
<h1>New Article</h1>
      <%= render "form", article: @article %>
   <div>

app/views/articles/show.html.erb
<div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
  <div class="card shadow-lg" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><h1><%= @article.title %></h1></h5>
     
      <p class="card-text"><p><%= @article.body %></p></p>
      <button type="button" class="btn btn-primary">
        <%= link_to "Edit", edit_article_path(@article), style: "color: white; text-decoration: none;" %>
      </button>
      <button type="button" class="btn btn-danger">
        <%= link_to "Delete", article_path(@article), style: "color: white; text-decoration: none;", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
      </button>
      <button type="button" class="btn btn-success">
        <%= link_to "Home", root_path, style: "color: white; text-decoration: none;" %>
      </button>
    </div>
  </div>
</div>

app/views/controllers/_controller.html.erb
<div id="<%= dom_id controller %>">
  <p>
    <strong>T:</strong>
    <%= controller.t %>
  </p>

</div>

app/views/controllers/_form.html.erb
<%= form_with(model: controller) do |form| %>
  <% if controller.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(controller.errors.count, "error") %> prohibited this controller from being saved:</h2>

      <ul>
        <% controller.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :t, style: "display: block" %>
    <%= form.text_field :t %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/controllers/edit.html.erb
<h1>Editing controller</h1>

<%= render "form", controller: @controller %>

<br>

<div>
  <%= link_to "Show this controller", @controller %> |
  <%= link_to "Back to controllers", controllers_path %>
</div>

app/views/controllers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Controllers</h1>

<div id="controllers">
  <% @controllers.each do |controller| %>
    <%= render controller %>
    <p>
      <%= link_to "Show this controller", controller %>
    </p>
  <% end %>
</div>

<%= link_to "New controller", new_controller_path %>

app/views/controllers/new.html.erb
<h1>New controller</h1>

<%= render "form", controller: @controller %>

<br>

<div>
  <%= link_to "Back to controllers", controllers_path %>
</div>

app/views/controllers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @controller %>

<div>
  <%= link_to "Edit this controller", edit_controller_path(@controller) %> |
  <%= link_to "Back to controllers", controllers_path %>

  <%= button_to "Destroy this controller", @controller, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <!-- <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>-->
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>